### ISSUE TITLE
PostgreSql表主键不是第一个时getGeneratedKeys方法报错的问题

### ISSUE THREAD

**Issue by 502647092** [jfinal/jfinal#122]
Pg表结构如下
```sql
CREATE TABLE public.keyword_report (
  biztime TIMESTAMP WITHOUT TIME ZONE, -- 报表业务时间
  impression BIGINT, -- 展现次数
  click BIGINT, -- 点击次数
  cost NUMERIC(18,2), -- 点击消耗，单位为元
  ctr NUMERIC(18,4), -- 点击率，保留4为小数
  ppc NUMERIC(18,2), -- 平均点击单价，单位为元
  adgroupid BIGINT, -- 推广单元id
  keywordid BIGINT, -- 关键词id
  sellerloginid CHARACTER VARYING(50), -- 会员账号
  id INTEGER PRIMARY KEY NOT NULL DEFAULT nextval('keyword_report_id_seq'::regclass)
);
```
由于ID字段处于最后一位 并且第一位的字段值不是数值类型
导致 `Model.java`
```java
/**
 * Get id after save method.
 */
private void getGeneratedKey(PreparedStatement pst, Table table, Config config) throws SQLException {
	String[] pKeys = table.getPrimaryKey();
	ResultSet rs = pst.getGeneratedKeys();
	for (String pKey : pKeys) {
		if (get(pKey) == null || config.dialect.isOracle()) {
			if (rs.next()) {
				Class colType = table.getColumnType(pKey);
				//由于Postgresql的getGeneratedKeys返回的是所有的数据所以这里不能用index的方式获取 应该用主键名称获取
				if (colType == Integer.class || colType == int.class)
					set(pKey, rs.getInt(1));
				else if (colType == Long.class || colType == long.class)
					set(pKey, rs.getLong(1));
				else
					set(pKey, rs.getObject(1));		// It returns Long object for int colType
			}
		}
	}
	rs.close();
}
```
产生的报错如下
```
com.jfinal.plugin.activerecord.ActiveRecordException: org.postgresql.util.PSQLException: 不良的类型值 int : 2017-04-06 00:00:00

	at com.jfinal.plugin.activerecord.Model.save(Model.java:424)
	at com.cnsixi.AliOpenPlatform.DataFetch.model.cnp4p.KeywordReport.fetchAndSave(KeywordReport.java:37)
	at com.cnsixi.AliOpenPlatform.DataFetch.model.cnp4p.KeywordReport.fetchAndSave(KeywordReport.java:28)
	at com.cnsixi.AliOpenPlatform.DataFetch.DataFetchTest.testFetchWxbInfo(DataFetchTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.postgresql.util.PSQLException: 不良的类型值 int : 2017-04-06 00:00:00
	at org.postgresql.jdbc.PgResultSet.toInt(PgResultSet.java:2832)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2047)
	at com.alibaba.druid.pool.DruidPooledResultSet.getInt(DruidPooledResultSet.java:147)
	at com.jfinal.plugin.activerecord.Model.getGeneratedKey(Model.java:441)
	at com.jfinal.plugin.activerecord.Model.save(Model.java:420)
	... 25 more

```
理论上 应该返回的是ID的值 但是却返回了`bizTime`导致类型转换错误
经过百度 PG 的 `getGeneratedKeys` 方法返回的是所有的字段数据 并不是生成的字段数据

**Comment by 502647092** [comment]
@jfinal

**Comment by jfinal** [comment]
这可能是 postgresql 的驱动程序引发的，换个驱动试试，如果不行的话，你试着改一下 if 语句，在  else if (colType == Long.class || colType == long.class) 这后面添加一个分支:
else if (colType == String.class)
    set(pKey, rs.getString(1));

记得搞定后回来分享一下，去 jfinal.com 社区反馈给我，github 我一般不上，看不到

**Comment by jfinal** [comment]
postgresql 的这个问题后来改进过，试用一下新版本，有问题还请告知，谢谢
