### ISSUE TITLE
template报错

### ISSUE THREAD

**Issue by sunlin901203** [jfinal/jfinal#140]
String result = Engine.use().getTemplate("table.html").renderToString(data);

报错日志
Exception in thread "main" java.lang.RuntimeException: File not found : null/table.html
	at com.jfinal.template.source.FileSource.getContent(FileSource.java:70)
	at com.jfinal.template.Engine.buildTemplateBySourceFactory(Engine.java:153)
	at com.jfinal.template.Engine.getTemplate(Engine.java:138)

**Comment by jfinal** [comment]
baseTemplatePath 未配置造成的，可以通过 Engine.use().setToClassPathSourceFactory() 让模板引擎去 class path 与 jar 包内去找模板，这样可以不必配置 baseTemplatePath:

`Engine.use().setToClassPathSourceFactory()`
