### ISSUE TITLE
关于新浪SAE部jfinal-weixin-demo时运行报错的问题

### ISSUE THREAD

**Issue by ichatter** [jfinal/jfinal#68]
demo上传至SAE，报:
  110.53.151.24 [19/Jul/2015:18:49:48 +0800] JAVA_Error: /msg
java.lang.StringIndexOutOfBoundsException: String index out of range: -6
at java.lang.String.substring(String.java:1875)
at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:68)
at com.sina.sae.servlet.SaeServletHandler.servletHandlerDoFilter(SaeServletHandler.java:56)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1328)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:476)
at com.sina.sae.servlet.SaeServletHandler.doHandle(SaeServletHandler.java:49)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:517)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:937)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:871)
at com.sina.sae.webapp.SaeWebAppContext.doScope(SaeWebAppContext.java:166)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:259)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
at com.sina.sae.handler.SaeUserInfoHandler.handle(SaeUserInfoHandler.java:109)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:305)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
at org.eclipse.jetty.server.Server.handle(Server.java:346)
at org.ecli yq173.javaruntime 

我暂时修改jfinal源码：
JFinal.java 第67行
将if (contextPathLength != 0)
改为if (contextPathLength < 0)
才运行正常。如果if (contextPathLength > 0)也报错

**Comment by ichatter** [comment]
找到问题了，SAE环境中，contextPath会默认加上前缀：/app版本号/appName
比如我的是：/1/qqlove2
所以相对于/msg，刚好下标超出6位
看来还得自己扩展一下JFinalFilter

**Comment by jfinal** [comment]
建议使用阿里云这样的 VPS，现在以校园学生购买才 9 块钱一个月，便宜好用，各类 XAE 都是阉割的东西，各种限制
