### ISSUE TITLE
RedisPlugin 直接使用 redis.incr增长键不存在值的Long型后， 使用redis取出会报异常 

### ISSUE THREAD

**Issue by zhiaixuexi** [jfinal/jfinal#92]
public static void main(String args[]){
		RedisPlugin rp = new RedisPlugin("statistics", "127.0.0.1", 6379, 1800);
		rp.start();
		redis =  Redis.use("statistics");
		Long incrRouteCounts = redis.incrBy("XXYY",100);
		redis.get("XXYY");//直接redis读不出来，怀疑存入的时候没做序列化
		
	}

报错如下：
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: java.lang.NullPointerException
	at com.jfinal.plugin.redis.serializer.FstSerializer.valueFromBytes(FstSerializer.java:78)
	at com.jfinal.plugin.redis.Cache.valueFromBytes(Cache.java:1211)
	at com.jfinal.plugin.redis.Cache.get(Cache.java:91)
	at com.clearclouds.driver.statistic.StatisticKit.main(StatisticKit.java:58)
Caused by: java.io.IOException: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241)
	at com.jfinal.plugin.redis.serializer.FstSerializer.valueFromBytes(FstSerializer.java:75)
	... 3 more
Caused by: java.lang.NullPointerException
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:350)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:325)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:305)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:239)
	... 4 more

**Comment by zhiaixuexi** [comment]
使用getCounter方法获取，但是对于Key存在判断，还是需要先用exists
